#!/bin/sh
set -euo pipefail

setUp() {
    cd $BASE/..
    export BUILDPACK_PATH=/tmp/common_spec
    mkdir -p $BUILDPACK_PATH
    rm -rf $BUILDPACK_PATH/dependencies
}

tearDown() {
    unset BUILDPACK_PATH
}

testCurlWhenTheFileDoesNotExistAsADependency() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH

    expected_output="Resource http://files.com/file.txt is not provided by this buildpack. Please upgrade your buildpack to receive the latest resources."

    assertEquals "$expected_output" "$(curl http://files.com/file.txt -s 2>&1)"
}

testCurlWhenTheFileFromTheUrlIsStreamed() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH
    touch $BUILDPACK_PATH/dependencies/http___files.com_file.txt
    echo 'some text' > $BUILDPACK_PATH/dependencies/http___files.com_file.txt

    assertEquals 'some text' "$(curl http://files.com/file.txt -s)"
}

testCurlWhenTheFileFromTheUrlIsStreamedWithOutputParameter() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH
    touch $BUILDPACK_PATH/dependencies/http___files.com_file.txt
    echo 'some text' > $BUILDPACK_PATH/dependencies/http___files.com_file.txt

    assertEquals 'some text' "$(curl http://files.com/file.txt -s -o -)"
}

testCurlWhenTheFileFromTheUrlIsWrittenToAnOutputFile() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH
    touch $BUILDPACK_PATH/dependencies/http___files.com_file.txt
    echo 'some text' > $BUILDPACK_PATH/dependencies/http___files.com_file.txt

    curl -s -L -o $BUILDPACK_PATH/dependencies/output_file.txt http://files.com/file.txt

    assertEquals 'some text' "$(cat $BUILDPACK_PATH/dependencies/output_file.txt)"
}

testCurlWhenTheFileFromTheUrlIsWrittenToAnOutputFileWhichIsNotProvided() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH
    touch $BUILDPACK_PATH/dependencies/http___files.com_file.txt
    echo 'some text' > $BUILDPACK_PATH/dependencies/http___files.com_file.txt

    curl -sO http://files.com/file.txt

    assertEquals 'some text' "$(cat $PWD/file.txt)"

    rm $PWD/file.txt
}

testCurlSupportsHttpsWhenOveridden() {
    mkdir $BUILDPACK_PATH/dependencies
    local PATH=./bin:$PATH
    touch $BUILDPACK_PATH/dependencies/https___files.com_file.txt
    echo 'some text' > $BUILDPACK_PATH/dependencies/https___files.com_file.txt

    assertEquals 'some text' "$(curl https://files.com/file.txt -s)"
}

# ==================================== Utilities ====================================

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $BASE/../vendor/shunit2
